export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_KEY_PRODUCTS = 'SET_KEY_PRODUCTS';
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const SET_TITLE_PRODUCTS = 'SET_TITLE_PRODUCTS';
